version: "3.9"

services:
  generator:
    image: node:18
    container_name: clock-generator
    volumes:
      - ./app:/app         # <- expose editable code
      - ./dist:/app/dist   # <- dist is output directory
    working_dir: /app
    command: sh -c "while true; do npm install && npm run generate; sleep 60; done"
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: clock-web
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - cloudflare-net
    depends_on:
      - generator
    restart: unless-stopped

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: clock-cloudflared
    networks:
      - cloudflare-net
    depends_on:
      - web
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}

networks:
  cloudflare-net:
