version: "3.9"

services:
  generator:
    image: node:18
    container_name: clock-generator
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run start
    restart: unless-stopped
    networks:
      - cloudflare-net

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: clock-cloudflared
    networks:
      - cloudflare-net
    depends_on:
      - generator
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN} --url http://clock-generator:8080

networks:
  cloudflare-net: